[package]
name = "stock_monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
yahoo_finance_api = "2.4.0"
tokio = { version = "1", features = ["full"] }
plotly = "0.7.0"
chrono = "0.4"
clap = { version = "4.0", features = ["derive"] }

